### ISSUE TITLE
Themes aren't escaping control characters properly?

### ISSUE THREAD

**Issue by PerilousApricot** [Bash-it/bash-it#270] opened 2014-02-19 22:18 UTC
Hey all,

First, thanks for bash-it, it's really been helpful! I have one bug I can't seem to figure out. FWIW, i'm running a terminal on OSX (mavericks) and sshing into a Centos5 machine (bash version 3.2.25(1)-release-(x86_64-redhat-linux-gnu)). With all of the themes I've tried (~5 of them), long command lines aren't properly line wrapped. I'm not sure of the best way to describe it, so I'll take a few screenshots

First login screen.
![screen shot 2014-02-19 at 4 12 53 pm](https://f.cloud.github.com/assets/93354/2212504/9326c760-99b3-11e3-9450-26efcc6b8ff0.png)
up-arrow a few times to a very long command line (this works)
![screen shot 2014-02-19 at 4 13 56 pm](https://f.cloud.github.com/assets/93354/2212506/9dbabaec-99b3-11e3-862e-9ab22b24fa2e.png)

change directories to a deep subdirectory within a git repository
![screen shot 2014-02-19 at 4 15 06 pm](https://f.cloud.github.com/assets/93354/2212507/a2af36d6-99b3-11e3-9314-6c0bb65e07b3.png)

up-arrow to the same command line (note the beginning of the line is off)
![screen shot 2014-02-19 at 4 15 31 pm](https://f.cloud.github.com/assets/93354/2212510/a92e7b70-99b3-11e3-95ec-a123a15f7787.png)

go down and up twice (bash miscounts the line again and moves up the terminal window)
![screen shot 2014-02-19 at 4 16 23 pm](https://f.cloud.github.com/assets/93354/2212511/aba7ff7a-99b3-11e3-908d-217183d58619.png)

Is it possible that the scm info isn't properly escaped? I tried poking around, but nothing jumps out at me.

**Comment by mattwilmott** [comment] 2015-01-20 04:11
It looks like the color codes are causing grief as well particularly with the 'pure' theme. Setting LC_ALL doesn't resolve the issue. I think the issue is they are non printable and related to http://tldp.org/HOWTO/Bash-Prompt-HOWTO/nonprintingchars.html

**Comment by trinitronx** [comment] 2016-01-08 23:55
Just ran into this problem while using the `bobby` theme, with the following plugins:

plugins:
 - base
 - explain
 - extract
 - osx
 - rvm
 - ssh

Line wrapping works fine when I'm using it on OSX Mavericks 10.9.5 with OS-shipped version of bash:

```
bash --version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

However, after starting a [`docker-machine` VM][1], with shared `/Users` folder... I can run a docker container based on CentOS 7, and because my home directory is mounted inside, it sources my `.bashrc`, including `~/.bash_it/bash-it.sh`.  Inside the container environment, I notice that long lines are not wrapping properly, and the `bobby` theme includes some 3-byte chars such as `☆`, and depending on `git status` for the directory I'm in, either one of: `✗` or `✓`.

When I put `export LC_ALL=en_US.UTF-8` in my `~/.bashrc` and re-run the Docker container, line wrapping works fine!

So the reason I'm posting this is to add my own testing results for `LC_ALL=en_US.UTF-8` fixing it on `CentOS 7`, and to suggest that docker is a good way to test bash-it against different Unix platforms & bash versions.

Tested against docker image based on the official CentOS 7 image (`FROM centos:centos7`):

```
$ CentOS Linux release 7.1.1503 (Core)
$ bash --version
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
```

[1]: https://docs.docker.com/machine/get-started/

**Comment by edubxb** [comment] 2016-02-04 21:41
I added a note to the README about this, so I will close the issue.

Thanks!

**Closed by edubxb** 2016-02-04 21:41 UTC
Labels: bug

**Comment by nwinkler** [comment] 2016-02-05 07:30
:+1:

**Comment by trinitronx** [comment] 2016-03-31 01:30
Started getting the bad line wrapping behavior again in an `Ubuntu 14.04.3 LTS` container, this time with error message:

```
bash: warning: setlocale: LC_ALL: cannot change locale
```

To fix it, I had to do this:

```
sudo apt-get update;  sudo apt-get upgrade -y locales

sudo locale-gen en_US.UTF-8
echo LANG=en_US.UTF-8 | sudo tee /etc/default/locale
```
