### ISSUE TITLE
_bash-it-clean-component-cache: command not found

### ISSUE THREAD

**Issue by daenney** [Bash-it/bash-it#1309] opened 2019-01-15 13:44 UTC
When installing bash-it with `--interactive` I'm getting this for everything I enable:

```
Would you like to enable the ag aliases? [y/N] y
/home/daenney/.bash_it/lib/helpers.bash: line 488: _bash-it-clean-component-cache: command not found
ag enabled with priority 150.
```

Same happens for plugins and completions.

**Comment by nwinkler** [comment] 2019-01-15 13:51
Thanks for reporting this, it seems to be a regression issue from #1273. @kigster Do you want to add a fix for this? The easiest way would be to check for the presence of the referenced function, and skip the call if the function does not exist...

**Comment by nwinkler** [comment] 2019-01-21 07:33
Thanks to @kylewelsby, this should be working again! Thanks for reporting and fixing this!

**Closed** 2019-01-21 07:33 UTC
Labels: NeedsPR, bug, help wanted

**Comment by kigster** [comment] 2019-01-21 16:09
Ahh good catch! Thanks for the fix.
