### ISSUE TITLE
problem with alias completion plugin

### ISSUE THREAD

**Issue by agentcobra** [Bash-it/bash-it#1166] opened 2018-04-02 14:52 UTC
Hi,
I've got a little problem with this plugin: https://github.com/Bash-it/bash-it/blob/6cf96b8f2477bd01624924a1d96ad321f17fccb4/plugins/available/alias-completion.plugin.bash
it's open each time my editor vim when I load the .bashrc file

I'm under arch with GNU bash, version 4.4.19(1)-release (x86_64-unknown-linux-gnu)

**Comment by agentcobra** [comment] 2018-04-02 14:54
may have link with #1158 ?

**Comment by nwinkler** [comment] 2018-04-03 06:03
This actually looks like a duplicate of #1030 - should be fixed with #1165, which I am about to merge in a moment.

Closing this as a duplicate...

**Closed by nwinkler** 2018-04-03 06:03 UTC

**Comment by agentcobra** [comment] 2018-04-03 07:28
thanks for PR #1165
