### ISSUE TITLE
complete: SUDO_EDITOR="emacsclient": no completion specification

### ISSUE THREAD

**Issue by greenrd** [Bash-it/bash-it#654] opened 2016-02-02 08:47 UTC
I've enabled quite a lot of stuff and got this error when opening a new tab:
```
bash: complete: SUDO_EDITOR="emacsclient": no completion specification
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-u user] file ...
```

after which bash starts and displays the fancy prompt.

**Comment by nwinkler** [comment] 2016-02-02 10:41
This is defined here: https://github.com/Bash-it/bash-it/blob/master/aliases%2Favailable%2Femacs.aliases.bash#L11

```
alias E='SUDO_EDITOR="emacsclient" sudo -e'
```

It looks like you have the `emacs` aliases enabled and have somehow run the `E` alias.

Can you try the following?

```
bash-it disable alias emacs
```

Then close the Terminal window and open a new one...

**Comment by greenrd** [comment] 2016-02-02 11:17
Yes, that avoided the issue, thanks. But the errors occurred on shell startup, so I'm not sure what was causing them.

**Comment by nwinkler** [comment] 2016-02-02 11:28
Not sure either, but I know that `sudo` is executed as part of some of the themes to show a visual indicator.

Can this ticket be closed?

**Comment by greenrd** [comment] 2016-02-02 14:04
I think it's still a bug.

**Comment by nwinkler** [comment] 2016-02-02 16:09
Can you provide more info on how to reproduce this? I don't have Emacs installed, but even if I enable the `emacs` aliases, I don't get this error.

Can you provide the following info:

* OS
* Version of Bash
* List of Aliases, Completions and Plugins enabled for Bash-it
* Bash-it Theme

**Comment by greenrd** [comment] 2016-02-03 18:13
OS: Linux (Fedora 23)

Version of bash: 4.3.42(1)-release

```
bash_it/aliases/enabled:
ag.aliases.bash  bundler.aliases.bash  clipboard.aliases.bash  docker.aliases.bash  fuck.aliases.bash  general.aliases.bash

.bash_it/completion/enabled:
awscli.completion.bash   bundler.completion.bash  docker.completion.bash  hub.completion.bash    npm.completion.bash     pip.completion.bash       ssh.completion.bash
bash-it.completion.bash  dirs.completion.bash     gradle.completion.bash  maven.completion.bash  packer.completion.bash  projects.completion.bash

.bash_it/plugins/enabled:
alias-completion.plugin.bash  base.plugin.bash     dirs.plugin.bash    explain.plugin.bash  fasd.plugin.bash  git-subrepo.plugin.bash  java.plugin.bash        jekyll.plugin.bash    projects.plugin.bash
aws.plugin.bash               browser.plugin.bash  docker.plugin.bash  extract.plugin.bash  git.plugin.bash   history.plugin.bash      javascript.plugin.bash  postgres.plugin.bash  ssh.plugin.bash
```

Theme: bobby

Also possibly relevant is that I chose to append the bash-it templates to my existing .bashrc file instead of overwriting it.

**Comment by edubxb** [comment] 2016-02-03 22:55
I reproduced the same error when enabling the emacs alias, I will dig into it...

**Comment by edubxb** [comment] 2016-02-03 23:14
Fixed, can you update and validate it?

Thanks!

**Comment by edubxb** [comment] 2016-02-04 20:47
I close this issue because is solved, @greenrd feel free to reopen if not.

**Closed by edubxb** 2016-02-04 20:47 UTC
