### ISSUE TITLE
Add command to bash-it to disable or enable SCM check

### ISSUE THREAD

**Issue by samuelecarpene** [Bash-it/bash-it#615] opened 2015-11-24 08:28 UTC
Sometimes i have a lot of files and shell slow down a lot.
I think that can be useful to add a command to disable/enable scm check withiout modifying the .bashrc file.

What do you think?

**Comment by nwinkler** [comment] 2015-11-24 09:18
Looks like a duplicate of #572 to me. Can you please check the available solutions there - it's possible that one of them is fixing your issue (e.g. the `git config` option described in https://github.com/Bash-it/bash-it/issues/572#issuecomment-139533806)

**Comment by samuelecarpene** [comment] 2015-11-24 11:10
The problem is the same.. but i suggest to add
 bash-it  enable scmcheck
 bash-it  disable scmcheck
to allow to enable or disable the functionality instead of the usage of EXPORT

**Comment by seefood** [comment] 2015-11-24 11:14
actually, if I want it in one terminal but not another (seems legit), then environment settings are the best way to go about it.

**Comment by nwinkler** [comment] 2015-11-24 11:18
Well, the commands suggested by @samuelecarpene could simply change the environment variables, that's really all there is to it...

Feel free to provide a PR to include this functionality...

Instead of `enable/disable` I would rather use something like `config`, to avoid confusing it with enabling/disabling plugins.

```
bash-it config theme.scm.check 1
```

Or something like that...

**Comment by edubxb** [comment] 2016-02-04 21:06
As @nwinkler points out, the are available solutions:

- setting the variable:

    `SCM_CHECK=false`

- using a git:

    `git config --add bash-it.hide-status 1`

But feel free to provide a PR.

Also, some speed improvements has landed into Bash-it checking git repository status in this PR #649, so the need to deactivate the git status check can be avoided (or not :stuck_out_tongue_winking_eye: ).

**Comment by NoahGorny** [comment] 2020-12-06 21:24
This issue is very stale, so I close it. Thanks for contributing and posting!

**Closed by NoahGorny** 2020-12-06 21:24 UTC
Labels: FeatureRequest, NeedsPR
