### ISSUE TITLE
Problems running install script

### ISSUE THREAD

**Issue by arimourao** [Bash-it/bash-it#879] opened 2017-01-07 10:34 UTC
Downloaded a ubuntu xenial vagrant box, cloned the repo to ~/.bash-it and running the install script with `sudo ./bash-it.sh` I run into the following errors:

ubuntu@ubuntu-xenial:~/.bash-it$ sudo ./bash_it.sh 
./bash_it.sh: line 32: /bin/bash/lib/composure.bash: Not a directory
./bash_it.sh: line 35: cite: command not found
./bash_it.sh: line 38: /bin/bash/themes/colors.theme.bash: Not a directory
./bash_it.sh: line 39: /bin/bash/themes/base.theme.bash: Not a directory
./bash_it.sh: line 47: /bin/bash/lib/*.bash: Not a directory
./bash_it.sh: line 54: _load_bash_it_files: command not found
./bash_it.sh: line 54: _load_bash_it_files: command not found
./bash_it.sh: line 54: _load_bash_it_files: command not found
./bash_it.sh: line 58: /bin/bash/lib/appearance.bash: Not a directory

**Comment by nwinkler** [comment] 2017-01-07 11:57
What happens when you run it without `sudo`?

**Comment by arimourao** [comment] 2017-01-07 12:32
Same thing. I also tried to install in my notebook running Debian 8 Jessie and runs into the same issue.

ubuntu@ubuntu-xenial:~/.bash-it$ ./bash_it.sh 
./bash_it.sh: line 32: /bin/bash/lib/composure.bash: Not a directory
./bash_it.sh: line 35: cite: command not found
./bash_it.sh: line 38: /bin/bash/themes/colors.theme.bash: Not a directory
./bash_it.sh: line 39: /bin/bash/themes/base.theme.bash: Not a directory
./bash_it.sh: line 47: /bin/bash/lib/*.bash: Not a directory
./bash_it.sh: line 54: _load_bash_it_files: command not found
./bash_it.sh: line 54: _load_bash_it_files: command not found
./bash_it.sh: line 54: _load_bash_it_files: command not found
./bash_it.sh: line 58: /bin/bash/lib/appearance.bash: Not a directory

**Comment by nwinkler** [comment] 2017-01-07 13:01
How about you run the actual install script (install.sh)? You're not supposed to run bash_it.sh directly 😝

**Comment by arimourao** [comment] 2017-01-07 14:55
Ok, my bad! But after I install, I'm prompted with:
To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

Then I Type:
ubuntu@ubuntu-xenial:~/.bash-it$ bash-it show completions
bash-it: command not found

**Comment by nwinkler** [comment] 2017-01-07 16:09
Right above that, the installer should have also printed the following:

```bash
Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source "$HOME/.bash_rc"'
```

Can you please give that a try? When you open a new tab in your terminal app, the `bash-it` function should be available.

**Comment by nwinkler** [comment] 2017-01-16 07:16
Closing this now, since there was no further feedback. Feel free to reopen if the problem persists.

**Comment by jaredmcateer** [comment] 2018-10-06 16:50
I can reproduce the problem. The read me `README.md`  instructs:

> Run **~/.bash_it/install.sh** (it automatically backs up your ~/.bash_profile or ~/.bashrc, depending on your OS)
(emphasis mine)

```bash
jared@shepardbook:~$ . ~/.bash_it/install.sh 
Installing bash-it
Backup file already exists. Make sure to backup your .bashrc before running this installation.
Would you like to overwrite the existing backup? This will delete your existing backup file (/home/jared/.bashrc.bak) [y/N] y
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] y
Your original .bashrc has been backed up to .bashrc.bak
sed: can't read /home/jared/template/bash_profile.template.bash: No such file or directory
Bash-it template has been added to your .bashrc
bash: /home/jared/lib/composure.bash: No such file or directory

Command 'cite' not found, did you mean:

  command 'scite' from deb scite
  command 'ctie' from deb texlive-binaries
  command 'cfte' from deb fte
  command 'vite' from deb vite

Try: sudo apt install <deb name>

bash: /home/jared/lib/helpers.bash: No such file or directory

Enabling reasonable defaults
_enable-completion: command not found
_enable-completion: command not found
_enable-plugin: command not found
_enable-plugin: command not found
_enable-alias: command not found

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source /home/jared/.bashrc'.

To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

To avoid issues and to keep your shell lean, please enable only features you really want to use.
Enabling everything can lead to issues.
jared@shepardbook:~$ source ~/.bashrc
jared@shepardbook:~$ bash-it show aliases
bash-it: command not found

```

However following your instructions in this issue I switched into `~/.bash_it` and ran `./install.sh` and everything worked.

```bash
jared@shepardbook:~$ cd .bash_it/
✔ ~/.bash_it [master|✔] 
10:44 $ ./install.sh 
Installing bash-it
Backup file already exists. Make sure to backup your .bashrc before running this installation.
Would you like to overwrite the existing backup? This will delete your existing backup file (/home/jared/.bashrc.bak) [y/N] y
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] y
Your original .bashrc has been backed up to .bashrc.bak
Bash-it template has been added to your .bashrc

Enabling reasonable defaults
bash-it enabled with priority 350.
system enabled with priority 350.
base enabled with priority 250.
alias-completion enabled with priority 365.
general enabled with priority 150.

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source /home/jared/.bashrc'.

To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

To avoid issues and to keep your shell lean, please enable only features you really want to use.
Enabling everything can lead to issues.
✔ ~/.bash_it [master|✔] 
10:44 $ source ~/.bashrc
✔ ~/.bash_it [master|✔] 
10:44 $ bash-it show aliases
Alias               Enabled?  Description
ag                    [ ]     the silver searcher (ag) aliases
ansible               [ ]     ansible abbreviations
apt                   [ ]     Apt and dpkg aliases for Ubuntu and Debian distros.
atom                  [ ]     Atom.io editor abbreviations
bundler               [ ]     ruby bundler
clipboard             [ ]     pbcopy and pbpaste shortcuts to linux
curl                  [ ]     Curl aliases for convenience.
docker                [ ]     docker abbreviations
docker-compose        [ ]     docker-compose abbreviations
emacs                 [ ]     emacs editor
fuck                  [ ]     
general               [x]     general aliases
git                   [ ]     common git abbreviations
gitsvn                [ ]     common git-svn abbreviations
heroku                [ ]     heroku task abbreviations
hg                    [ ]     mercurial abbreviations
homebrew              [ ]     homebrew abbreviations
homebrew-cask         [ ]     homebrew-cask abbreviations
homesick              [ ]     homesick aliases
jitsu                 [ ]     jitsu task abbreviations
kubectl               [ ]     kubectl aliases
laravel               [ ]     laravel artisan abbreviations
maven                 [ ]     maven abbreviations
npm                   [ ]     common npm abbreviations
osx                   [ ]     osx-specific aliases
phoenix               [ ]     phoenix abbreviations
pyrocms               [ ]     pyrocms abbreviations
rails                 [ ]     rails abbreviations
svn                   [ ]     common svn abbreviations
systemd               [ ]     systemd service
textmate              [ ]     textmate abbreviations
tmux                  [ ]     Tmux terminal multiplexer
todo.txt-cli          [ ]     todo.txt-cli abbreviations
vagrant               [ ]     vagrant aliases
vault                 [ ]     vault aliases
vim                   [ ]     vim abbreviations
yarn                  [ ]     yarn package manager aliases

to enable an alias, do:
$ bash-it enable alias  <alias name> [alias name]... -or- $ bash-it enable alias all

to disable an alias, do:
$ bash-it disable alias <alias name> [alias name]... -or- $ bash-it disable alias all
```

**Comment by nwinkler** [comment] 2018-10-15 06:39
Thanks for the update on this? Anybody willing to look into this issue to provide a PR fixing this? Looks like something is wrong with the paths in the install script...

**Closed** 2019-01-08 14:47 UTC
Labels: NeedsMoreInfo, NeedsPR, help, installation

**Comment by mmudge** [comment] 2021-03-16 15:58
I ran into a similar problem with OSX using zsh, changing my shell to bash `chsh -s /bin/bash` and restarting my terminal fixed the problem for me.
