### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by ellerbrock** [Bash-it/bash-it#859] opened 2016-12-14 21:10 UTC
hi there,

maybe i'm blind but i can't find any license information.
i would appreciate if you make this clear by adding a license into the git root.

thx

**Comment by nwinkler** [comment] 2016-12-15 07:07
Duplicate of #512 - you might want to add your thoughts there. I'm closing this one, but feel free to chime in on the other one.

**Closed by nwinkler** 2016-12-15 07:07 UTC
