### ISSUE TITLE
bash: warning: setlocale: LC_ALL: cannot change locale (en_uS.UTF-8): No such file or directory

### ISSUE THREAD

**Issue by sudoharun** [Bash-it/bash-it#2206] opened 2023-05-06 19:02 UTC
Either I'm dumb or something because I can't figure out how to get rid of this error. 
![bruh](https://user-images.githubusercontent.com/123123333/236641931-f8672c95-5ad1-4d52-92e2-4143539897a0.png)

On the main page under themes it says this:
> NOTE: Bash-it and some themes use UTF-8 characters, so to avoid strange behavior in your terminal, set your locale to `LC_ALL=en_US.UTF-8` or the equivalent to your language if it isn’t American English.

So I should be able to get rid of this error without having to change my locale to en_US.

My locale is set to en_GB.UTF-8:
![bruh2](https://user-images.githubusercontent.com/123123333/236641938-79535a49-b5ab-452f-9c77-48d4627f4166.png)

What am I missing to keep my locale set to en_GB.UTF-8 and get rid of this error? (I would prefer not to install en_US locale because I'm in the UK)

Edit: Using sexy theme

**Comment by sudo-harun** [comment] 2023-05-18 09:45
closing since I moved to zsh after a re-install

**Comment by mefor44** [comment] 2024-11-14 21:05
I have the saem error, can we reopen this?

**Comment by seefood** [comment] 2024-11-15 16:36
do you have the locale generated? Can you show this error is because of Bash-it and not happening in general anyway?

**Comment by akinomyoga** [comment] 2024-11-15 16:54
As I commented in https://github.com/Bash-it/bash-it/issues/2269#issuecomment-2478178460, this error is caused by Bash-it assuming the existence of a specific locale `en_US.UTF-8`. Even if the locales are generated, if `en_US.UTF-8` is not included in the set of the enabled locales, it doesn't exist. In general, one should not assume the locale `en_US.UTF-8` is present in the system. The solution is also given in https://github.com/Bash-it/bash-it/issues/2269#issuecomment-2478178460.

**Closed** 2024-11-19 06:38 UTC
Labels: help wanted
