### ISSUE TITLE
bash_completion problem - usage line while open new terminal

### ISSUE THREAD

**Issue by Ygarr** [Bash-it/bash-it#809] opened 2016-10-23 10:08 UTC
1. Install Bash-it
2. Open terminal tab
3. shows:
complete: usage: complete [-abcdefgjksuv] [-pr] [-DE] [-o option] [-A action] [-G globpat] [-W wordlist]  [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]
 ~ 
4. If uninstall  bash_completion:
bash: /usr/share/bash-completion/bash_completion: No such file or directory
  ~ 
5. If install last version of bash_completion from git:
the same as in 3.

6. If install last release 2.4 of bash_completion from sources:
the same as in 3.

ALSO:
http://imgur.com/GR7WcrN.
The system is:
 
 OS: Debian unstable sid
 Kernel: x86_64 Linux 4.8.3-towo.1-siduction-amd64
 Uptime: 1h 41m
 Packages: 3222
 Shell: bash 4.4.0
 Resolution: 1366x768
 DE: LXDE
 WM: OpenBox
 WM Theme: Bear2
Adwaita [GTK2]

 Icon Theme: Paper
 Font: Sans 10
 CPU: Intel Core i5-4200U CPU @ 2.6GHz
 GPU: Mesa DRI Intel(R) Haswell Mobile 
 RAM: 1325MiB / 7910MiB

**Comment by edubxb** [comment] 2016-10-24 18:51
I can confirm this issue, that is generated by this alias:

https://github.com/Bash-it/bash-it/blob/master/aliases/available/general.aliases.bash#L47

**Comment by nwinkler** [comment] 2016-10-25 14:14
So is this issue happening when the alias (`--`) is enabled? Or when it is not enabled?

**Comment by edubxb** [comment] 2016-10-25 20:23
Well, the issue really appears when the "alias completion plugin" is enabled and tries to add completion to the ` --` alias.

**Comment by nwinkler** [comment] 2016-10-26 13:12
Thanks for the details! So possible fixes include:

* Removing the `--` altogether. This would start to fail again if someone manually defines the `--` alias.
* Fixing the "alias completion plugin" to avoid creating the completion for the `--` alias. This has the downside that it feels like a band aid - no guarantee that the same thing won't happen with a different alias.

Any others?

**Comment by p3k** [comment] 2016-10-26 13:22
Happens to me on OS X 10.11.6, too. The culprit seems to be this line in the temporary file, `/tmp/alias-completion-*.tmp`: 

```bash
complete -F _alias_completion::-- --
```

If you execute it (in an initialised bash-it shell) you get the same error as described in the issue:

```bash
complete -F _alias_completion::-- --
# complete: usage: complete [-abcdefgjksuv] [-pr] [-DE] [-o option] [-A action] [-G globpat] [-W wordlist]  [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]
```

Is it perhaps necessary to escape the `--` somehow?

**Comment by nwinkler** [comment] 2016-10-26 13:46
Since `cd -` shouldn't take any parameters, there shouldn't be any completion required for it at all.

Out of the two options I presented above, I guess the second one (trying to filter out the `--` alias when generating the completions) sounds like the better choice to me. Opinions?

**Comment by edubxb** [comment] 2016-10-26 19:29
According this excerpt from Bash manual:

> **SHELL BUILTIN COMMANDS**
>        Unless  otherwise  noted, each builtin command documented in this section as accepting options preceded by - accepts -- to signify the end of the options.  The :, true, false, and test builtins do not accept options and do not
>        treat -- specially.  The exit, logout, return, break, continue, let, and shift builtins accept and process arguments beginning with - without requiring --.  Other builtins that accept arguments but are not specified as accept‐
>        ing options interpret arguments beginning with - as invalid options and require -- to prevent this interpretation.

I made a fix in #812

**Comment by edubxb** [comment] 2016-10-28 18:31
@Ygarr @p3k this issue is fixed in master now, can you update (`bash-it update`) and confirm it?

**Comment by p3k** [comment] 2016-10-29 08:50
+1 

works for me, thanks a lot 😺

**Comment by nwinkler** [comment] 2016-10-29 10:59
Awesome, thanks for verifying - closing this now.

I'm thinking about setting up a Vagrant machine with a recent Bash version to run through these scenarios - need to find the time to do that, though...

**Closed by nwinkler** 2016-10-29 10:59 UTC

**Comment by dnichk** [comment] 2016-11-16 15:08
I'm still having this issue, and my bash-it says it is up to date.

```
complete: usage: complete [-abcdefgjksuv] [-pr] [-DE] [-o option] [-A action] [-G globpat] [-W wordlist]  [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]
(06:56:31) ○ [dustin@archibald] 
```
THen I checked if I had updates to do...
```
(07:06:51) ○ [dustin@archibald] ~ 
→ bash-it update
Bash-it is up to date, nothing to do!
```

Ideas?
