### ISSUE TITLE
Autocompletion seems not working for git

### ISSUE THREAD

**Issue by kirk86** [Bash-it/bash-it#1611] opened 2020-06-05 10:38 UTC
Hi, just a quick question. I have enable git plugin along with base and some other plugins but when I'm in a repository entering commands I get no autocompletion. Is there any issues with autocompletion?

**Comment by nwinkler** [comment] 2020-06-05 12:34
Can you please post an example of what you're trying to do? I'll try to reproduce this.

I'm not aware of any issues.

**Comment by kirk86** [comment] 2020-06-05 13:57
Sure thing, here's a description.

1. Fresh installation of bash-it
2. Clone a git repo from my projects
3. cd into the repo
4. execute `git st` for `git status` or `git pu` for `git push` and press tab to autocomplete.

Nothing comes up, also from the plugins I only have git enabled.
Am I doing sth wrong here?

**Comment by davidpfarrell** [comment] 2020-06-05 21:26
Greetings,

It looks like you're interested in using the git auto-completions.

Just to confirm, bash-it's git `plugin` is different than its git `completion`:

```
$ bashit search git

      aliases:  git gitsvn
      plugins:  autojump git git-subrepo jgitflow jump
  completions:  git git_flow git_flow_avh
```

If you haven't already, try:
```
$ bashit enable completion git
```

You'll need to start a fresh terminal session ( or use `bashit reload` if you've enabled it) as the completions are only executed when bash-it is initialized.

Let us know if that helps,

-DF

**Comment by kirk86** [comment] 2020-06-05 22:50
@davidpfarrell Great thanks a lot for the clarifications. I just have a last question. From my understanding it seems that for the completions to work one needs to have the equivalent plugin enabled, is that correct or would the completions still work?

**Comment by davidpfarrell** [comment] 2020-06-06 00:09
Hi @kirk86,

I do not believe you need the plugin to be enabled to use the completions.

I *believe* the plugin just adds functions that the user can use to aid their git usage.

I would recommend you disable the plugin and enable the completions.

DO lemme know if something breaks :)

-DF

**Comment by kirk86** [comment] 2020-06-06 11:15
Hi @davidpfarrell, that's great thanks for all the help. Appreciate it!

**Comment by nwinkler** [comment] 2020-06-08 07:52
Thanks for clarifying this, @davidpfarrell - closing this now.

**Closed by nwinkler** 2020-06-08 07:52 UTC
