### ISSUE TITLE
subl alias

### ISSUE THREAD

**Issue by herroannekim** [Bash-it/bash-it#973] opened 2017-06-03 21:02 UTC
I've updated bash-it, sublime text 3, homebrew, cask--the whole shabang.  Nevertheless my subl alias isn't working.  I've been banging my head at this problem for an embarrassing 3 hours.  Does anyone have anymore troubleshooting tips?  Thanks.

**Comment by nwinkler** [comment] 2017-06-04 10:32
Can you show the output of the following commands?

* `bash-it show plugins`
* `alias subl`

Let's see what those are and then we can look into what might be wrong.

**Comment by herroannekim** [comment] 2017-06-04 17:20
Output from `bash-it show plugins`
`$ bash-it show plugins
Plugin              Enabled?  Description
alias-completion      [x]     Automatic completion of aliases
autojump              [ ]     Autojump configuration, see https://github.com/wting/autojump for more details
aws                   [ ]     AWS helper functions
base                  [x]     miscellaneous tools
battery               [ ]     display info about your battery charge level
boot2docker           [ ]     Helpers to get Docker setup correctly for boot2docker
browser               [ ]     render commandline output in your browser
chruby-auto           [ ]     load chruby + auto-switching (from /usr/local/share/chruby)
chruby                [ ]     load chruby                  (from /usr/local/share/chruby)
dirs                  [ ]     directory stack navigation
docker-compose        [ ]     Helper functions for using docker-compose
docker-machine        [ ]     Helpers to get Docker setup correctly for docker-machine
docker                [ ]     Helpers to more easily work with Docker
edit-mode-emacs       [ ]     Enable emacs editing mode
edit-mode-vi          [ ]     Enable vi editing mode
explain               [ ]     mankier.com explain function to explain other commands
extract               [ ]     one command to extract them all...
fasd                  [ ]     initialize fasd (see https://github.com/clvv/fasd)
fzf                   [ ]     load fzf, if you are using it
gh                    [ ]     load gh, if you are using it (DEPRECATED, use hub instead)
gif                   [ ]     gif helper functions
git-subrepo           [ ]     load git-subrepo if you are using it, and initialize completions
git                   [ ]     git helper functions
go                    [ ]     go environment variables & path configuration
gradle                [ ]     Add a gw command to use gradle wrapper if present, else use system gradle
hg                    [ ]     hg helper functions
history               [ ]     history manipulation
hub                   [ ]     load hub, if you are using it
java                  [ ]     Java and JAR helper functions
javascript            [ ]     download jquery files into current project
jekyll                [ ]     manage your jekyll site
jenv                  [ ]     load jenv, if you are using it
latex                 [ ]     use mactex
less-pretty-cat       [ ]     pygmentize instead of cat to terminal if possible
nginx                 [ ]     manage your nginx service
node                  [ ]     Node.js helper functions
nvm                   [ ]     node version manager configuration
osx-timemachine       [ ]     OS X Time Machine functions
osx                   [ ]     osx-specific functions
percol                [ ]     Search&Select history and fasd with percol
pipsi                 [ ]     load pipsi, if you are using it
plenv                 [ ]     plenv plugin for Perl
postgres              [ ]     postgres helper functions
projects              [ ]     add "export PROJECT_PATHS=~/projects:~/intertrode/projects" to navigate quickly to your project directories with `pj` and `pjo`
proxy                 [ ]     Proxy Tools
pyenv                 [ ]     load pyenv, if you are using it
python                [ ]     alias "shttp" to SimpleHTTPServer
rails                 [ ]     Helper functions for Ruby on Rails
rbenv                 [ ]     load rbenv, if you are using it
ruby                  [ ]     ruby and rubygems specific functions and settings
rvm                   [ ]     load rvm, if you are using it
sdkman                [ ]     Load Software Development Kit Manager
ssh                   [ ]     ssh helper functions
subversion            [ ]     svn helper functions
textmate              [ ]     set textmate as a default editor
tmux                  [ ]     make sure that tmux is launched in 256 color mode
tmuxinator            [ ]     sources tmuxinator script if available
todo                  [ ]     Todo.txt integration
virtualenv            [ ]     virtualenvwrapper helper functions
visual-studio-code    [ ]     Defines the `code` executable for Visual Studio Code on OS X
xterm                 [ ]     automatically set your xterm title with host and location info
z                     [ ]     maintains a jump-list of the directories you actually use
                              z is DEPRECATED, use fasd instead
z_autoenv             [ ]     source into environment when cding to directories

to enable a plugin, do:
$ bash-it enable plugin  <plugin name> [plugin name]... -or- $ bash-it enable plugin all

to disable a plugin, do:
$ bash-it disable plugin <plugin name> [plugin name]... -or- $ bash-it disable plugin all`

Output from `alias subl`
`$ alias subl
-bash: alias: subl: not found`

**Comment by nwinkler** [comment] 2017-06-05 14:11
OK, that helps. I should have asked for the output of `bash-it show aliases` though, don't remember why I asked for the plugins output...

It looks like the `subl` alias is not defined. Can you please try the following?

* Run `bash-it enable alias osx`
* Then run `reload` or open a new terminal window/tab
* Try running `subl` again
* If that still does not work, show the output of `alias subl` again

The `subl` alias is defined in the `osx.aliases.bash` file, so let's try to enable that and then see how far we can get.

**Comment by herroannekim** [comment] 2017-06-05 15:02
WOW! MAGIC!  Thanks!

So you have to enable the bash-it aliases in order to define them and use them?

**Comment by nwinkler** [comment] 2017-06-05 15:09
Yes, by default, Bash-it does not enable any of the functionality provided in the optional aliases/plugins/completions. You have to enable what you want.

Run `bash-it show aliases` (or with `plugins` or `completions`) to show what's enabled.

Feel free to close this ticket if the issue is resolved.

**Closed** 2017-06-05 15:22 UTC
