### ISSUE TITLE
Include starship like prompt

### ISSUE THREAD

**Issue by TarunavBA** [Bash-it/bash-it#1996] opened 2021-12-15 06:12 UTC
## Expected Behavior

It should give the default starship prompt

## Current Behavior

Currently there is no prompt like that. But I guess it will be. 

## Possible Solution

Make a theme like starship prompt.

## Context

I have always been jealous of the [Starship](https://starship.rs/) prompt. So if you make one like that I would always feel happy.

**Comment by davidpfarrell** [comment] 2021-12-19 21:52
Greetings !  So I took some time to look into it ...

_Starship_ is not written in bash (its written in Rust), so the project proper could never be an integrated part of Bash-It.

You might consider trying to create a similar theme for Bash-it with similar segments, formatting, etc ... 

**BUT** This probably isn't necessary for a couple of reasons:

* Starship comes with _direct_ support for bash:
  * `eval "$(starship init bash)`
* Starship makes *every* effort to be compatible with other scripts that use prompt_command, debug traps, etc.
* Starship is available in many different distribution formats and is quite easy to install.

As such, you _should_ be able to run Starship prompt alongside Bash-It.

The key to doing this is to disable Bash-It's builtin themes.  Here's a quick example that I used locally:

_.bash_profile_
```
# NOTE: Empty ("") means No Theme, where as unset means Default Theme (bobby)
export BASH_IT_THEME=""

... # Rest of Bash-It Setup
source "$BASH_IT"/bash_it.sh

# Init Starship
eval "$(starship init bash)
```

Give that a try and see how it goes !  I'll be interested in hearing if you find any bugs with using Starship alongside Bash-It.

NOTE: If your goal really was to discuss creating a _Starship-like_ theme in pure bash, we can discuss that, but I'm not sure its necessary given how easy it is to install and use Starship.

**Comment by TarunavBA** [comment] 2021-12-20 06:04
Ahemmm.. ummm... But... I'm using windows 7 and I cannot install starship prompt in it so that's why I'm asking you this feature request. 😭

**Comment by TarunavBA** [comment] 2021-12-20 06:04
@davidpfarrell

**Comment by davidpfarrell** [comment] 2021-12-20 17:08
@TarunavBA How are you using Bash-It on windows?

Starship should work fine under WSL but also has direct support for PowerShell.

You may want to reach out the Starship support community for configuring it for your setup.

**Comment by TarunavBA** [comment] 2021-12-20 17:47
> @TarunavBA How are you using Bash-It on windows?
> 
> Starship should work fine under WSL but also has direct support for PowerShell.
> 
> You may want to reach out the Starship support community for configuring it for your setup.

@davidpfarrell I'm using it in `git bash` for windows

**Comment by davidpfarrell** [comment] 2021-12-20 20:00
Starship appears to be confirmed-working in `git bash` 
* [mentioned in bash init script generator](https://github.com/starship/starship/blob/671365b5057cabb4e30a661a54c0b84dccdda37a/src/init/mod.rs#L101)
* [Path issue a user filed that was confirmed working](https://github.com/starship/starship/issues/2986)

I think you can spend a little time configuring your git bash setup and Starship will work fine.

Again I recommend you reach out to Starship support for issues with your setup - It appears your configuration is properly supported.

Feel free to close this issue, or leave it open If you want to put together a Pull Request to emulate some of Starship's features/look/feel in Bash-It - But since Starship has proper Bash support I wouldn't think it would be necessary.

Good luck !

**Comment by TarunavBA** [comment] 2021-12-21 03:02
Ok @davidpfarrell I'll try as suggested in #2986 and get back to you if it still spits errors.

**Closed** 2022-12-05 22:01 UTC
Labels: feature request
