### ISSUE TITLE
Add releases/versioning

### ISSUE THREAD

**Issue by kbsali** [Bash-it/bash-it#1038] opened 2017-09-14 11:54 UTC
It would be great to start tagging versions of the bash-it to make it easier to know if we have the latest version available, rollback to an older version in case of issues, etc...

Thanks for this great project!

**Comment by nwinkler** [comment] 2017-09-14 19:15
That's a nice suggestion, and something I've thought about myself, too. For some other projects I use Git Flow, with an unstable "develop" branch, and a stable "master" branch for releases.

For Bash-it, this might not be as easy as one might think, though. A couple of questions/food for thought:

* What does a "version" mean for Bash-it? What goes into a release, and how do we decide when to cut a new release? Not sure whether a version number (like Bash-it v2.3.5) has a real meaning - what are the "rules" for what causes a major version increase, what a minor version, what a patch?
* When someone creates a Pull Request for a bug fix or a feature request, and we merge that, do we always automatically create a new release for that? Or do we wait until we have collected a couple of changes and then create a release?
* Version/Release management creates some overhead, someone would have to maintain the release numbers in GitHub, and sooner or later, people are going to ask for a change log or release notes. Someone needs to create/update/maintain all of this.

Thinking about these has so far stopped me from setting up proper releases for Bash-it. Every change (once merged) goes directly into the "master" branch, and people updating or cloning will always get the latest version.

Is there a compelling reason for having release numbers/versions that would make a particular task easier? Let's discuss...

**Comment by kbsali** [comment] 2017-09-18 09:21
It's just "nice" to know what you are "running" v1.0.23 and that the latest is v1.0.43... which means you know that you are "missing" 20 "updates" (although minors) and you can even check the changes through github's releases page.
The "overhead" is really minor : YOU as the project owner decide whether it makes sense to tag the master branch (which would be the one and only branch to tag), full stop. It only becomes an overhead if you want to maintain a changelog for every release...

right now it's : 
```
Bash-it successfully updated.

Migrating your installation to the latest version now...

All done, enjoy!
```
or 
```
Bash-it is up to date, nothing to do!
```

but there is not way to get back to the repo and check the changes... which i would love to be able to check!

**Comment by tswicegood** [comment] 2017-09-19 16:10
I disagree that the overhead is minor for this. Right now the workflow is merge to master and folks can do a `git pull` if they want the latest changes with no overhead except pressing Merge as a maintainer. Adding a release process means we have to tag things and figure out what the flow to `master` should be. I think @nwinkler's question is still yet-to-be-answered:

> Is there a compelling reason for having release numbers/versions that would make a particular task easier?

I could possibly make a case for having version numbers tied to dates and adopting a git-flow like merge to `develop` and release to `master` workflow. Then version numbers would be something like `v17.09` and `v17.10`. Again though, I'm not sure what problem that solves.

Reading between the lines, I think you're after a little more feedback on what's happening @kbsali. How many updates are being applied, how far behind are you, and so on? I agree that some feedback on what is happening during `bash-it update` would be nice. Displaying something like the output of:

```console
git log --merges HEAD...origin/master --format=%b
```

We could use that to get at the number of changes since your update as well. Taking it a step further, adding a `[Y/n]` prompt gives you the option to abort and jump into the specifics if you have questions. Right now running `bash-it update` requires a lot of trust. 😄

**Comment by nwinkler** [comment] 2017-09-19 17:04
Great answer - thanks @tswicegood!

**Comment by kbsali** [comment] 2017-09-20 09:01
I give up! :)

I believe it is a "common best practice" to version software and there are tools for automating the release process making the "overhead" minor (sorry to insist! ;)).
As you say @tswicegood "`bash-it update` requires a lot of trust" and the solution you propose (`git log --merges HEAD...origin/master --format=%b`) is an overhead for the user! :) Which is ok, I can live with it!
Btw, I see there are 66 issues opened, sometimes having releases would help spot if the user is running the latest version of bash-it or not.

**Comment by nwinkler** [comment] 2017-09-20 11:56
No no no, please don't give up 😄 It's users like you that provide input and feedback to open-source projects, and projects like Bash-it rely on feedback - please keep the suggestions coming. Just because we don't agree 100% on something does not mean that you should stop with providing feedback.

There's a couple of things here:
* Yes, I agree that adding a version number to software releases is a best practice - I follow that for most of my work. I see Bash-it as an exception for the reasons I've given above: It's not clear to me what constitutes a release or a version. If we had created a new release for each of the 600+ Pull Requests, we would have had to create and manage a lot of releases. Unless we come up with a good definition as to when to create a major, a minor or a patch release, I don't see an easy way out of this. Bash-it is not a logging library, or a database driver, where I'm really interested in the differences between the versions - for me, running the latest version of Bash-it is usually good enough. You seem to have a different need, and we should try to address that.
* If there is a tool that makes creating/maintaining versions and releases on GitHub trivial, then please feel free to provide a link or a description to such a tool. If there is a tool that automatically creates a (meaningful) change log and creates a GitHub release, then I'm interested in seeing that - and we should consider using it.
* I think you got @tswicegood's suggestion wrong. He was not suggesting that you run the `git log` command yourself. The way I understood it, we should add the output of `git log` (or similar) to the `bash-it update` command so that you get to see what is going to be updated.

Having said that, I think that the problem is more complex. You're probably not interested in seeing a list of commits, but rather want a meaningful change log that shows the changes in high-level terms, for example "Added a plugin for garblefoo" instead of the 17 commits that were done for adding the insanely complex garblefoo plugin. Right?

I'm more than happy to discuss the requirements with you, and I'm sure that we can come up with some meaningful and useful additions. We'll have to balance the administrative overhead, of course...

Reopening, since I find the discussion interesting and would like to learn more about what you're looking for.

**Comment by nwinkler** [comment] 2017-09-20 11:58
Re-reading your last sentence, would it make sense to include something like "There have been XX commits in the master branch since you last updated Bash-it" as part of the `bash-it update` command, and then a link to the "commits" page on GitHub? At least as a starting point...

**Comment by tswicegood** [comment] 2017-09-20 15:27
> No no no, please don't give up 😄 It's users like you that provide input and feedback to open-source projects, and projects like Bash-it rely on feedback - please keep the suggestions coming. Just because we don't agree 100% on something does not mean that you should stop with providing feedback.

💯  * 👍 

----- 

> I think you got @tswicegood's suggestion wrong. He was not suggesting that you run the git log command yourself. The way I understood it, we should add the output of git log (or similar) to the bash-it update command so that you get to see what is going to be updated.

Yeah! I'm thinking the workflow goes like:

```console
$ bash-it update
There are 3 updates to apply…
Update or view the details? [Y/v/n] v
  - Add plugin for acme widgets
  - Update git completion
  - New theme called awesomeness
Apply? [Y/n] Y
All done, enjoy
$
```

That could be done by the user right now, but I think we should do it as part of `update` – possibly with a `-y|--yes` flag that continues the current behavior.

**Comment by kbsali** [comment] 2017-09-27 20:16
@tswicegood is awesome! :+1:

**Comment by nwinkler** [comment] 2017-09-28 06:05
The question is how we get from the list of commits (which might be rather verbose) to a concise list of changes like shown in your example?

**Comment by tswicegood** [comment] 2017-09-28 18:40
No need to change anything. Merge commits via PR produce a great changelog. Against current `master`, I ran `git reset --hard 2742adbe`, then ran this command:

```console
$ git log --merges --format="  - %b" HEAD...origin/master
  - Update brew completion
  - Move enabled components to a global directory
  - Fix execution of trap DEBUG on subshells
```

The two key things here are `--merges` which only shows merge commits (i.e., the way we merge PRs), and `--format="  - %b"` which updates to show only the body message. By default the commit message for PRs merged contains the subject with the PR # and such and the title as the body. To that end, I'm gonna change the settings to only allow merge commits of PRs so we have this as an option.

If you wanna get fancy, you can do some fun stuff with `awk` and prefix all of those with the PR # and such too.

**Comment by nwinkler** [comment] 2017-09-29 06:10
That's great - no need to squash commits or anything! Since we're using Push Requests for changes, every change to `master` should result in a merge and will show up in this log - cool!

**Comment by michaelsbradleyjr** [comment] 2018-08-03 01:05
I would like to see tags on the repo, even if they simply marked points in time as Bash-it involves. Maybe you could tag on the first day of each month?

Use case: https://github.com/embark-framework/embark-docker/blob/master/Dockerfile

I'm specifying dependency versions in a Dockerfile to aim for reproducible builds (well, as reproducible as possible when it comes to this kind of thing).  I could download a commit-specific gzip'd tarball for Bash-it from GitHub, but that's a bit of a hassle, and there's no option for git-cloning a specific commit. So, currently, I'm leaving Bash-it un-versioned. I could fork and create tags myself, might end up doing that.

**Comment by nwinkler** [comment] 2018-08-03 06:35
@michaelsbradleyjr Thanks for the request - I understand the requirement and the desire to have a tagged version available at all times.

Unfortunately, I don't have the time to go through this process each month... Are you aware of an automated way of doing this?

**Closed** 2018-12-02 18:55 UTC

**Comment by tswicegood** [comment] 2018-12-02 18:56
Here's what the current implementation of `bash-it update` looks like:

```console
$ bash-it update
544a092: Show upgrades before blindly upgrading (Travis Swicegood)

Would you like to update to 544a092? [Y/n]
Bash-it successfully updated.

Migrating your installation to the latest version now...

All done, enjoy!```
