### ISSUE TITLE
Command not found when entering a new session.

### ISSUE THREAD

**Issue by agucova** [Bash-it/bash-it#733] opened 2016-05-28 22:45 UTC
```
ForgottenPlayer@:~$ bash
bash: update_terminal_cwd: command not found
bash: autojump_add_to_database: command not found
bash: update_terminal_cwd: command not found
ForgottenPlayer@:~$ 
```
So, this only happens when I manually invoke a "bash", when I open a new Terminal window it doesn't show. (I'm on OSX)

**Comment by nwinkler** [comment] 2016-05-29 08:26
Duplicate of #708 and #709 - closing.

**Closed by nwinkler** 2016-05-29 08:26 UTC
