### ISSUE TITLE
Encountering error when using 'sudo' plugin

### ISSUE THREAD

**Issue by Fooughhy** [Bash-it/bash-it#1591] opened 2020-05-12 06:58 UTC
Hi!
Just wanna say I love the versatility this tool brings me when using bash.

Wanted to try out the 'sudo' plugin as I find myself forgetting to use it many times after having written a long line in the terminal.
But I get this error when using it:
> bash: bash_execute_unix_command: cannot find keymap for command

So, for clarity, I have enabled the 'sudo' plugin, write something in the terminal and double-click the 'Esc' key. Then this error appear in the terminal.
I updated bash-it today, so I should have the most recent version.

**Comment by nwinkler** [comment] 2020-05-13 08:30
Which version of Bash are you running?

Also tagging @ucomesdag since they added the plugin.

**Comment by Fooughhy** [comment] 2020-05-13 10:07
My `bash --version` output is the following:
> GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
>Copyright (C) 2016 Free Software Foundation, Inc.
>License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
>
>This is free software; you are free to change and redistribute it.
>There is NO WARRANTY, to the extent permitted by law.

**Comment by davidpfarrell** [comment] 2020-05-13 17:09
Greetings all,

[Googling for "bash_execute_unix_command: cannot find keymap for command"](https://www.google.com/search?q=bash_execute_unix_command%3A+cannot+find+keymap+for+command&rlz=1C5CHFA_enUS771US771&oq=bash_execute_unix_command%3A+cannot+find+keymap+for+command&aqs=chrome..69i57.336j0j7&sourceid=chrome&ie=UTF-8) suggests that the issue is related to competing key bindings in your system.

Are you aware of any other key bindings in your system with the escape key?

**Comment by Fooughhy** [comment] 2020-05-16 05:44
Not aware of any unfortunately... Tried to find a way to show keybinds for a key, but haven't been able to...

**Comment by snex** [comment] 2020-05-18 01:14
I am seeing this issue as well. Fresh install.

```
$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ucomesdag** [comment] 2020-05-19 20:53
> I am seeing this issue as well. Fresh install.

@snex & @Fooughhy what OS are you using, so I can try to reproduce it?

**Comment by snex** [comment] 2020-05-19 21:06
Ubuntu 18.04

Linux snex-desktop 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ucomesdag** [comment] 2020-05-20 05:07
> Ubuntu 18.04
> 
> Linux snex-desktop 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I will try to reproduce it coming days and keep you updated.

**Comment by Fooughhy** [comment] 2020-05-20 05:41
Using Linux Mint 19.3 here.
![neofetch](https://user-images.githubusercontent.com/6977416/82409119-51a37100-9a6d-11ea-8518-52fb7df86f6f.png)

**Comment by davidpfarrell** [comment] 2020-05-20 21:11
Greetings all,

Although it a may be a bit verbose, it might also be useful to past some `bind` configuration data here for review.

i.e From with a terminal instance that is exhibiting the issue, run these commands and save the output:
```
$ bind -p # List function names and bindings
$ bind -s # List key sequences that invoke macros and their values
$ bind -v # List variable names and values
$ bind -X # capital 'X' - List key sequences bound with -x and associated commands
```

Some of these may have no output.  `-s` and `-X` are both empty on my system.

Use 'code fences'  for displaying the data, ie:
````
```
$ bind -v

set bind-tty-special-chars on
set blink-matching-paren off
   ...

```
````

I'm hoping that, with some of this data for review, we *might* be able to identify a pattern.

**Comment by snex** [comment] 2020-05-20 21:25
https://gist.github.com/snex/6318e1f2ba849ffb0d48d4c1de7ec487

**Comment by Fooughhy** [comment] 2020-05-21 04:46
These are the files containing the output of those commands. `bind -s` didn't have any output, and is thus not included.


[bindp.txt](https://github.com/Bash-it/bash-it/files/4660632/bindp.txt)
[bindv.txt](https://github.com/Bash-it/bash-it/files/4660633/bindv.txt)
[bindX.txt](https://github.com/Bash-it/bash-it/files/4660635/bindX.txt)

**Comment by davidpfarrell** [comment] 2020-05-21 21:18
@snex , @Fooughhy , 

Thank you both for sharing your configurations.

I think I found the issue:

Found within *both* of your `bind -p` settings:
```
"\e\e[C": forward-word
"\e\e[D": backward-word
```

Looking at the top links in a google search for [`"\e\e[C": forward-word`](https://www.google.com/search?q=%22%5Ce%5Ce%5BC%22%3A+forward-word) shows they are configurations for using arrow keys to quickly move between words on the command line.

I confirmed that enabling either of these causes the issue associated with this ticket:

```
$ echo hello

# escape-scape
$ sudo echo hello

$ bind '"\e\e[C": forward-word'

# escape-scape
readline: forward-word: no key sequence terminator
```

I was not able to find any page that suggested these were automatically created anywhere, so are either of you aware of how these bindings are being enabled in your system?

**Comment by snex** [comment] 2020-05-21 21:43
I have no idea where that came from, and I have never used Esc+arrow to navigate words on the command line, since Ctrl+arrow does the job already.

It appears to be set in my /etc/inputrc file.

**Comment by davidpfarrell** [comment] 2020-05-21 21:46
@snex wrote:
> It appears to be set in my /etc/inputrc file.

Are there any comments in/around the entry?

**Comment by snex** [comment] 2020-05-21 21:54
Only this:
"# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving"

It is also right next to the binds that define the Ctrl+arrow movement.

**Comment by Fooughhy** [comment] 2020-05-22 05:34
Thank you for your patience, man! It works after I removed those and restarted my PC. I though it  would only require a reload of bash-it, but it seems a restart is necessary.

**Comment by nwinkler** [comment] 2020-05-23 16:07
Thanks for the great analysis, @davidpfarrell!

Closing this now, since it seems to be resolved.

**Closed by nwinkler** 2020-05-23 16:07 UTC
