### ISSUE TITLE
Theme preview not working

### ISSUE THREAD

**Issue by 99thpixel** [Bash-it/bash-it#1198] opened 2018-05-31 20:55 UTC
I get the bellow output when I enter the "BASH_PREVIEW=true reload":

```
○ → BASH_PREVIEW=true reload
-bash: reload: command not found
```

Any tips on how to get it working?

**Comment by nwinkler** [comment] 2018-06-01 06:20
Good one, nice find!

You need to do this instead: `BASH_PREVIEW=true bash-it reload`

The `reload` alias has been deprecated in favor of the the `bash-it reload` command.

I've updated the documentation as well - thanks for reporting this issue!

**Comment by dimitrov-adrian** [comment] 2018-06-27 14:48
I also have this error when doing ```bashit update```

**Comment by nwinkler** [comment] 2018-07-18 06:30
Can you please confirm whether you are doing `bash-it update` or `bashit update`?

**Comment by dimitrov-adrian** [comment] 2018-07-18 09:33
@nwinkler both commands produce the same error

```
❯ bash-it update
Bash-it successfully updated.

Migrating your installation to the latest version now...

All done, enjoy!
-bash: reload: command not found
```

**Comment by nwinkler** [comment] 2018-07-19 06:42
@dimitrov-adrian I can confirm that I get the same error, it looks like the `update` function still uses the old `reload` alias, which has been deprecated/removed.

I'll provide a fix for this...

**Closed** 2018-07-19 07:10 UTC
