### ISSUE TITLE
syntax error in alias_completion

### ISSUE THREAD

**Issue by albasili** [Bash-it/bash-it#1995] opened 2021-12-14 22:13 UTC
Hi folks,

I love `bash-it` and I use it since a while, recently though I changed job and sure enough porting my config from the old environment turned out to be more painful than it should really be. After installing `bash-it` I have the following message everytime I source my `.bashrc`:

```
bash: /tmp/alias_completion-18586PeVE7O: line 2612: syntax error near unexpected token `;'
bash: /tmp/alias_completion-18586PeVE7O: line 2612: `                        COMP_WORDS=(cdconfigs; cd bash ${COMP_WORDS[@]:1})'
bash: cdconfigs;: command not found
bash: /tmp/alias_completion-18586PeVE7O: line 2617: syntax error near unexpected token `}'
bash: /tmp/alias_completion-18586PeVE7O: line 2617: `                    }'
bash: /tmp/alias_completion-9137AYAjnR: line 2612: syntax error near unexpected token `;'
bash: /tmp/alias_completion-9137AYAjnR: line 2612: `                        COMP_WORDS=(cdconfigs; cd bash ${COMP_WORDS[@]:1})'
bash: cdconfigs;: command not found
bash: /tmp/alias_completion-9137AYAjnR: line 2617: syntax error near unexpected token `}'
bash: /tmp/alias_completion-9137AYAjnR: line 2617: `                    }'
```

the `cdconfigs` seems an alias defined in my environment (not sure where).
Any idea?

**Comment by NoahGorny** [comment] 2021-12-18 13:02
Hi @albasili
What exactly is the `cdconfig` alias?
You can use `alias cdconfigs` to find the definition.

**Comment by albasili** [comment] 2021-12-20 22:34
the `cdconfigs` is an alias defined in my environment (maybe through system level settings, I haven't investigated yet), but it's just  a shortcut for `cd /home/configs` which is where our EDA team is storing config files for module loading (it's an IC desing company with several CAD tools to perform our tasks, configured with a horde of module files).

I'm not entirely sure though why the definition of this alias led to the error reported above, and what is /tmp/alias_completion...? Is it created on the fly?

**Comment by NoahGorny** [comment] 2022-01-07 06:57
Hi @albasili, sorry for the delay.
I want to see the full definition of the alias- we might have a bug in case of specific alias definitions.

I am more interesting in special quirks in the alias (weird quoting, subshells, etc) and not in the actual work the alias does 😄

**Comment by gaelicWizard** [comment] 2022-01-15 08:21
@albasili, this is due to how aliases work. Aliases are interpreted during *input*, not during evaluation. So, if the alias is defined after `completion/alias` then it will not be a valid command. This *might* be fixed in my #2044, but it's hard to test without knowing the alias definition and where it's defined (i.e. before or after `bash_it.sh` is loaded).

Aside: yes, that temp file is created on the fly and then `source`d.

**Comment by adpande** [comment] 2022-02-15 12:05
I installed Bash-it today and facing the similar issue.
``` bash
bash: /tmp/alias_completion-22072wI5NhT: line 1: syntax error near unexpected token `cd'
bash: /tmp/alias_completion-22072wI5NhT: line 1: `cd -'
```
This happens every time I start a new terminal. Here is the full generated file:
[alias_completion-22072wI5NhT.txt](https://github.com/Bash-it/bash-it/files/8068870/alias_completion-22072wI5NhT.txt)

**Comment by gaelicWizard** [comment] 2022-02-15 17:31
Thank you for the samples! @adpande @ajax711 

I'll check them out right now

**Comment by gaelicWizard** [comment] 2022-02-15 20:05
I've just opened #2091 which quotes the additions to `$COMP_WORDS`, which should address the original issue that @albasili was experiencing. 

For @adpande @ajax711, I'd love if you could take #2091 for a spin and let me know if that alsö resolves your `cd -` issue.

**Comment by gaelicWizard** [comment] 2022-02-15 20:22
Ok, now I've specifically reproduced the `cd -` error and I believe I've fixed it.

**Closed** 2022-02-16 20:12 UTC

**Comment by adpande** [comment] 2022-02-16 20:15
Just pulled the updated code. It is fixed!!!! Thanks a lot for the wonderful software!
