### ISSUE TITLE
Unable to complete an update

### ISSUE THREAD

**Issue by simonbcn** [Bash-it/bash-it#2094] opened 2022-02-17 14:26 UTC
I have installed bash-it in a Raspberry Pi and today I've executed: `bash-it update` and an endless cycle of :confused:  ? has begun, in this gif you can see what happens:

![Peek 17-02-2022 15-12](https://user-images.githubusercontent.com/428231/154500224-16a8d011-924a-40bc-a545-62c5dd2107fc.gif)

Does it seem to run a `less` over and over again showing one line at a time of the changelog? I have to press `Q` every time.

```
$ bash --version
GNU bash, version 5.1.4(1)-release (aarch64-unknown-linux-gnu)
....

$ bash-it version
Version type: dev
Current git SHA: 86c1e3c on 2022-01-09T01:13:49+02:00
Commit info: https://github.com/Bash-it/bash-it/commit/86c1e3c
Compare to latest: https://github.com/Bash-it/bash-it/compare/86c1e3c...master

$ bash-it doctor all
DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: vendor: Loading "preexec"...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: general: Loading component...
WARN: aliases: general: Command 'gshuf' does not exist!
DEBUG: aliases: systemd: Loading component...
DEBUG: plugin: base: Loading component...
WARN: plugin: base: Command 'markdown' does not exist!
WARN: plugin: base: Command 'mkisofs' does not exist!
DEBUG: plugin: history: Loading component...
DEBUG: plugin: less-pretty-cat: Loading component...
WARN: plugin: less-pretty-cat: Command 'pygmentize' does not exist!
DEBUG: plugin: man: Loading component...
DEBUG: plugin: sudo: Loading component...
DEBUG: plugin: thefuck: Loading component...
WARN: plugin: thefuck: Command 'thefuck' does not exist!
DEBUG: completion: system: Loading component...
DEBUG: completion: bash-it: Loading component...
DEBUG: plugin: alias-completion: Loading component...
DEBUG: plugin: history-search: Loading component...
DEBUG: plugin: history-substring-search: Loading component...
DEBUG: core: reloader: Loading "bobby" theme...
WARN: themes: base: Command 'battery_percentage' does not exist!
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
WARN: custom: example: Command 'reload' does not exist!
```

**Comment by gaelicWizard** [comment] 2022-02-17 19:46
@simonbcn, you can temporarily bypass this by setting `export GIT_PAGER=`. I'm looking in to the cause...

**Comment by simonbcn** [comment] 2022-02-18 08:25
Is it necessary to show the entire changelog? It is very long: 1040 lines! :open_mouth:

**Comment by tbhaxor** [comment] 2022-02-24 07:45
@gaelicWizard We can show the summary of changes like

```
n files changes
m additions and p deletions
old version - 
new version - 
```

Even showing files changes and by whom doesn't make sense to me.

**Comment by gaelicWizard** [comment] 2022-02-24 20:44
Maybe a list of *only* the PRs that have been merged? That way, there's a brief change log but without individual commits... I dunno, what do people expect from an update function? For full releases, we should have some kind of Release Notes...

**Comment by NoahGorny** [comment] 2022-03-01 21:57
Hi @simonbcn, seems like this is a problem with our latest stable version, but should not happen to you in the latest master. I will push out a new stable version (finally!)

**Closed by NoahGorny** 2022-03-01 21:57 UTC
Labels: bug:general
