### ISSUE TITLE
[Bug]: install  bash_it on PVE debian-12-genericcloud-amd64-20230612-1409.qcow2

### ISSUE THREAD

**Issue by mffan0922** [Bash-it/bash-it#2208] opened 2023-06-23 15:14 UTC
### Expected behavior

I expect it successfully installed

### Current behavior

when I run `bash isntall.sh`, the output tells the following:

[ 0 root@Template-Debian12-Bak .bash_it]# bash install.sh
install.sh: line 186: cd: install.sh: Not a directory
Installing bash-it
Backup file already exists. Make sure to backup your .bashrc before running this installation.
Would you like to overwrite the existing backup? This will delete your existing backup file (/root/.bashrc.bak) [y/N] y
Overwriting backup...
Would you like to keep your .bashrc and append bash-it templates at the end? [y/N] y
Your original .bashrc has been backed up to .bashrc.bak
sed: can't read /template/bash_profile.template.bash: No such file or directory
Bash-it template has been added to your .bashrc
**install.sh: line 207: /vendor/github.com/erichs/composure/composure.sh: No such file or directory
install.sh: line 209: /lib/utilities.bash: No such file or directory
install.sh: line 211: /lib/log.bash: No such file or directory
install.sh: line 212: cite: command not found
install.sh: line 214: /lib/helpers.bash: No such file or directory

install.sh: line 223: _bash-it-profile-load: command not found**

Installation finished successfully! Enjoy bash-it!
To start using it, open a new tab or 'source ~/.bashrc'.

To show the available aliases/completions/plugins, type one of the following:
  bash-it show aliases
  bash-it show completions
  bash-it show plugins

To avoid issues and to keep your shell lean, please enable only features you really want to use.
Enabling everything can lead to issues.

### Possible solution

I don't know, probably it is the system that cannot fit

### Steps to reproduce

it's a little bit complicated....

1. install PVE
2. create a vitual machine using debian-12-genericcloud-amd64-20230612-1409.qcow2, https://cloud.debian.org/images/cloud/bookworm/20230612-1409/
3. and install bash it, that's it

### Bash-it version

latest

### List of enabled plugins, themes and aliases

cannot install, so...

### Bash version

GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)

### Operating system and version

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)" VERSION_CODENAME=bookworm ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### bash-it doctor output

```
# How to get: bash-it doctor
```

### Your ~/.bashrc

```bash
# How to get: cat ~/.bashrc
```
nothing related to bash it

**Comment by cornfeedhobo** [comment] 2023-10-27 13:13
@mffan0922 I'm going to close this as not reproducable and it being so long since the report. If you remember, do you know if this was installed using git or with a zipped archive?

**Closed by cornfeedhobo** 2023-10-27 13:13 UTC
Labels: bug:general
