### ISSUE TITLE
Why my aliases broke the battery on theme

### ISSUE THREAD

**Issue by Wabri** [Bash-it/bash-it#1561] opened 2020-04-13 14:28 UTC
I have a bash_aliases import on my bashrc, but if I use it with bash_it the percentage of battery on the prompt return a -1 value.

I put this lines before the bash_it template on bashrc:
```
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
```

With those the battery_percentage return the -1 value if I remove them battery_percentage return the correct value.

I dont think that my aliases can broke some of those functionality.

My aliases:
```
alias ls='exa'
alias ll='exa -l'
alias la='exa -al'
alias grep='rg'
```

**Comment by Wabri** [comment] 2020-04-13 14:32
Spot the issue: the grep alias change the return of the battery plugin because i use ripgrep instead of the grep.

I solve the problem by update grep with the absolute path /usr/bin/grep on the plugins/available/battery.plugin.bash script.

Can be solve in other way?

**Comment by davidpfarrell** [comment] 2020-04-13 17:19
Greetings.

Bash-it is a bit fragile in that it doesn't try to isolate itself from users aliasing well-known system utils (i.e grep, awk, sed, etc) as you're doing here.

But it doesn't feel like like all of bash-it is having issues, just the battery plugin.

I would be interested to know which line(s) in the battery plugin are behaving differently with ripgrep.

@Wabri : Can you spend a few minutes and determine *exactly* which grep statement(s) cause the issue?  i.e which line number(s) within the `battery.plugin.bash` file and which grep statement (some lines have multiple grep statements).

Also:
* Q: Is your bash-it installation up to to date?
* Q: What version of ripgrep are you using?
* Q: Can you show the output of this command:
```type rg```

A quick review of the grep statements in the plugin show they seem mostly safe:

_grep statements ordered by complexity_
```
grep 'state'
grep percentage

grep -i BAT

grep -q 'discharging'

grep -q "off-line"
grep -q "on-line"

grep -q 'AC Power'
grep -q 'Battery Power'

grep -q 'BatteryStatus=1'
grep -q 'BatteryStatus=2'

grep -q '"ExternalConnected" = No'
grep -q '"ExternalConnected" = Yes'

grep -o "[0-9]\+"
grep -o '[0-9]\+'

grep -q 'charging\|fully-charged'
```

Perhaps one of the more complex grep clauses is causing the issue, but really these aren't too complex.

It may be more related to exit coding handling - The battery plugin does seem to rely on grep exit codes a lot. Perhaps ripgrep has different exit codes than grep under some conditions.

@Wabri please let us know what you find out,

-DF

PS: Its is worth pointing out that ripgrep is not intended to be a full drop-in replacement for grep:
* [RipGrep FAQ: Can ripgrep replace grep?](https://github.com/BurntSushi/ripgrep/blob/ecec6147d117da638c933cf103a3ea14ce87102d/FAQ.md#can-ripgrep-replace-grep)

**Comment by nwinkler** [comment] 2020-04-13 17:25
Thanks for chiming in, @davidpfarrell! I was going to say as well that aliasing a different command to `grep` feels quite invasive... We have more than 140 usages of `grep` in Bash-it - I really don't want to review all of them.

FWIW we could change all occurrences of `grep` to `command grep`, which should always use the command instead of an alias, but then we'd probably have to do the same with other commands just to be sure.

@Wabri What's your use case for wanting to use `grep` as an alias for `rg`? Typing `rg` instead of `grep` is shorter...

I would still be interested in the analysis to see which instance of `grep` is failing in the battery plugin.

**Comment by davidpfarrell** [comment] 2020-04-13 17:30
> FWIW we could change all occurrences of `grep` to `command grep`, ...

I've been thinking we might come up with convention like `bashit_grep` which gets defined at bashit startup.  Doing this for system utils that bashit relies on would give us isolation but also give us a chance to use logic to define the values, i.e. imagine `bashit_uuidgen` where the logic to define it could include cascading checks for multiple tools, OS checks, etc.

**Comment by nwinkler** [comment] 2020-04-13 18:34
Yes, something like that. We'd have to come up with a list of tools we want to do this for - would you include things like `awk`, `sed` or `find` as well? Doing that would isolate us from changes that users make in their tool definition, but at the same time, it would make the code less readable, and would probably increase the review effort for Pull Requests...

**Comment by Wabri** [comment] 2020-04-14 10:06
> But it doesn't feel like like all of bash-it is having issues, just the battery plugin.

That is because I have enabled only those 3 plugins:

- alias-completion 
- base
- battery 

I try one plugin at time to see if I get some error. 

> @Wabri : Can you spend a few minutes and determine exactly which grep statement(s) cause the issue? i.e which line number(s) within the battery.plugin.bash file and which grep statement (some lines have multiple grep statements).

Sure I can do that.

https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/plugins/available/battery.plugin.bash#L60
The last grep generate the problem.

I try run the line but ripgrep seems not working with that particular regex. The man page of both are the same:

```
       -o, --only-matching
              Print only the matched (non-empty) parts of a matching line,  with  each
              such part on a separate output line.
```

I ran this command `upower --show-info $(upower --enumerate | grep -i BAT) | grep percentage | command grep -o "[0-9]\+" | head -1` and the output is 29, but with ripgrep there is no output. I don't know how to debug it better than this.

> Q: Is your bash-it installation up to to date?

Yes, I install bashit yesterday.

> Q: What version of ripgrep are you using?

I'm on debian 10, I installed with the official repository and the version is:
```
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

> Q: Can you show the output of this command: type rg

`rg is /usr/bin/rg`

> @Wabri What's your use case for wanting to use grep as an alias for rg? Typing rg instead of grep is shorter...

I always used grep and now I want to try the **ripgrep** command, but I'm automatically typing grep so I created that alias to force the usage of rg. When I specifically want to use grep I use the absolute path /usr/bin/grep.

> Yes, something like that. We'd have to come up with a list of tools we want to do this for - would you include things like awk, sed or find as well? Doing that would isolate us from changes that users make in their tool definition, but at the same time, it would make the code less readable, and would probably increase the review effort for Pull Requests...

Yes I think replace every command like awk, sed and grep will drop a lot the readability of the code. Maybe create a function **bashit_awk** or **__sed** could be the solution, but I really dont know if it worth the cost of doing that.

**Comment by Wabri** [comment] 2020-04-14 13:27
I test more function and also myip not working because of grep, I think is the -o option that cause the problem, changing grep with command grep or /urs/bin/grep solve the problem.
With this in mind I found other section that may cause the same output:

- https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/plugins/available/base.plugin.bash#L40
- https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/themes/hawaii50/hawaii50.theme.bash#L87
- https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/completion/available/makefile.completion.bash#L20
- https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/plugins/available/jekyll.plugin.bash#L40
- https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/plugins/available/jekyll.plugin.bash#L41
- https://github.com/Bash-it/bash-it/blob/c9dc334981682a23c9448ce69db05476c57813f5/plugins/available/base.plugin.bash#L40

**Comment by davidpfarrell** [comment] 2020-04-14 16:55
@Wabri, Thanks for the detailed research / response !

At first, I thought the issue might be related to you using `v0.10.0`, since thats from 2018 and the most recent version is `v12.0.1` !

I decided to install both versions and check for msyelf.

It turns out that the issue is the `\+` in the grep regex.

By default, grep uses "POSIX Basic Regular Expressions"

_bash man page_
```
Basic vs Extended Regular Expressions
       In basic regular expressions the meta-characters ?, +, {, |, (, and )
       lose their special meaning; instead use the backslashed versions \?,
       \+, \{, \|, \(, and \).
```

However, ripgrep does not support these types of regex (nor will it ever):

_ripgrep faq page_
```
Here are some cases where you might not want to use ripgrep...

* Are you writing portable shell scripts intended to work in a variety of 
 environments? Great, probably not a good idea to use ripgrep! ripgrep
 has nowhere near the ubiquity of grep, so if you do use ripgrep, you might
 need to futz with the installation process more than you would with grep.

* Do you care about POSIX compatibility? If so, then you can't use ripgrep
 because it never was, isn't and never will be POSIX compatible.
```

With that ...

As much as I think an effort to help bash-it isolate itself from the user's environment is probably a decent idea worth pursuing,  I think the correct action here is to advise you *not* to alias grep to ripgrep.

I think you put your whole system at risk of issues like these since you are very likely going to encounter shell scripts outside of bash-it that will rely on grep's default regex engine.

Good luck on your journey to learn ripgrep - Now that I have it installed, I will likely play around with it more myself - But I know now not to alias it to grep ;-)

**Comment by nwinkler** [comment] 2020-04-15 06:31
I agree with @davidpfarrell - the best course of action will be for you to not define that alias...

FWIW if you're looking at alternatives to `grep`, I really like these:

* `ack`: https://beyondgrep.com
* `ag` (The Silver Searcher): https://github.com/ggreer/the_silver_searcher
* `pt` (The Platinum Searcher): https://github.com/monochromegane/the_platinum_searcher

An additional search tool that I use quite often is `sack` (https://github.com/sampson-chen/sack), which wraps both `ack` and `ag`, presenting the results in a really cool way. I probably use `sack`/`sag` the most out of these...

Closing this issue now, since this seems to be resolved.

**Closed by nwinkler** 2020-04-15 06:31 UTC
